//Base Logic: Derived from scrape_highlands.js by Milly Gunn

const fs = require('fs');

const BASE_URL = "https://query.wikidata.org/sparql";

//Searching for all geological peaks (Q8502) to ensure 50+ results
//This SPARQL code was Generated by Gemini
const SPARQL_QUERY = `
SELECT DISTINCT ?itemLabel ?coord ?elevation WHERE {
  ?item wdt:P31/wdt:P279* wd:Q8502; 
        wdt:P625 ?coord.
  
  bind(geof:longitude(?coord) as ?lon)
  bind(geof:latitude(?coord) as ?lat)
  
  # Lanzarote Bounding Box
  FILTER(?lon > -13.9 && ?lon < -13.3 && ?lat > 28.8 && ?lat < 29.5)

  OPTIONAL { ?item wdt:P2044 ?elevation. }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}
LIMIT 300`;


//ADAPTED: fetchWikidata
//Inherits Milly Gunn's async pattern but targets JSON API endpoints.

async function fetchWikidata(query) {
    const url = `${BASE_URL}?query=${encodeURIComponent(query)}&format=json`;
    const response = await fetch(url, {
        headers: {
            "User-Agent": "LanzaroteProject/1.0",
            "Accept": "application/sparql-results+json"
        }
    });

    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    return await response.json();
}

//Extracts numerical Lat/Lon from WKT string format.
function parsePoint(pointStr) {
    const match = pointStr.match(/Point\(([-\d.]+) ([-\d.]+)\)/);
    return match ? { lon: parseFloat(match[1]), lat: parseFloat(match[2]) } : null;
}

//main execution flow from Milly Gunn
async function main() {
    try {
        console.log("Fetching geological data...");
        const data = await fetchWikidata(SPARQL_QUERY);
        const bindings = data.results.bindings;

        const results = bindings.map(b => {
            const pos = parsePoint(b.coord.value);
            return {
                name: b.itemLabel.value,
                lat: pos ? pos.lat : null,
                lon: pos ? pos.lon : null,
                elevation: b.elevation ? parseFloat(b.elevation.value) : 0
            };
        });

        //fs.writeFileSync pattern
        fs.writeFileSync('volcanoes_data.json', JSON.stringify(results, null, 2));
        console.log(`✅ Success! Found ${results.length} points.`);
    } catch (error) {
        console.error("Error:", error.message);
    }
}

main();